-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.date_dim
(
    date_key serial NOT NULL,
    date date NOT NULL,
    year smallint NOT NULL,
    quarter smallint NOT NULL,
    month smallint NOT NULL,
    week smallint NOT NULL,
    day smallint NOT NULL,
    is_weekend boolean,
    PRIMARY KEY (date_key)
);

CREATE TABLE IF NOT EXISTS public.customers_dim
(
    customer_key serial NOT NULL,
    customer_id integer NOT NULL,
    customer_name character varying(50) NOT NULL,
    customer_contact_name character varying(50) NOT NULL,
    customer_address character varying(50) NOT NULL,
    customer_city character varying(20) NOT NULL,
    customer_postal_code character varying(10) NOT NULL,
    customer_country character varying(15) NOT NULL,
    PRIMARY KEY (customer_key)
);

CREATE TABLE IF NOT EXISTS public.employees_dim
(
    employee_key serial NOT NULL,
    employee_id integer NOT NULL,
    last_name character varying(15) NOT NULL,
    first_name character varying(15) NOT NULL,
    birth_date timestamp without time zone NOT NULL,
    photo character varying(25) NOT NULL,
    notes character varying(1024) NOT NULL,
    PRIMARY KEY (employee_key)
);

CREATE TABLE IF NOT EXISTS public.product_supplier_dim
(
    product_supplier_key serial NOT NULL,
    product_id integer NOT NULL,
    product_name character varying(50) NOT NULL,
    category_id integer NOT NULL,
    category_name character varying(25) NOT NULL,
    category_description character varying(255) NOT NULL,
    supplier_id integer NOT NULL,
    supplier_name character varying(50) NOT NULL,
    supplier_contact_name character varying(50) NOT NULL,
    supplier_address character varying(50) NOT NULL,
    supplier_city character varying(20) NOT NULL,
    supplier_postal_code character varying(10) NOT NULL,
    supplier_country character varying(15) NOT NULL,
    supplier_phone character varying(15) NOT NULL,
    product_unit character varying(25) NOT NULL,
    PRIMARY KEY (product_supplier_key)
);

CREATE TABLE IF NOT EXISTS public.sales_fact
(
    sales_key serial NOT NULL,
    date_key integer NOT NULL,
    customer_key integer NOT NULL,
    employee_key integer NOT NULL,
    product_key integer NOT NULL,
    product_price numeric NOT NULL,
    order_quantity integer NOT NULL,
    shipper_key integer NOT NULL,
    order_id integer NOT NULL,
    order_detail_id integer NOT NULL,
    dollar_sales numeric NOT NULL,
    PRIMARY KEY (sales_key)
);

CREATE TABLE IF NOT EXISTS public.shipper_dim
(
    shipper_key serial NOT NULL,
    shipper_id integer NOT NULL,
    shipper_name character varying(25) NOT NULL,
    shipper_phone character varying(15) NOT NULL,
    PRIMARY KEY (shipper_key)
);

ALTER TABLE IF EXISTS public.sales_fact
    ADD FOREIGN KEY (date_key)
    REFERENCES public.date_dim (date_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_fact
    ADD FOREIGN KEY (customer_key)
    REFERENCES public.customers_dim (customer_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_fact
    ADD FOREIGN KEY (employee_key)
    REFERENCES public.employees_dim (employee_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_fact
    ADD FOREIGN KEY (product_key)
    REFERENCES public.product_supplier_dim (product_supplier_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_fact
    ADD FOREIGN KEY (shipper_key)
    REFERENCES public.shipper_dim (shipper_key) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;




CREATE TABLE IF NOT EXISTS public.sales_fact
(
    sales_key serial NOT NULL,
    date_key integer NOT NULL,
    customer_key integer NOT NULL,
    employee_key integer NOT NULL,
    product_key integer NOT NULL,
    product_price numeric NOT NULL,
    order_quantity integer NOT NULL,
    shipper_key integer NOT NULL,
    order_id integer NOT NULL,
    order_detail_id integer NOT NULL,
    dollar_sales numeric NOT NULL,
    PRIMARY KEY (sales_key)
);



ALTER TABLE sales_fact
ALTER COLUMN date_key DROP NOT NULL,
ALTER COLUMN customer_key DROP NOT NULL,
ALTER COLUMN employee_key DROP NOT NULL,
ALTER COLUMN product_key DROP NOT NULL,
ALTER COLUMN product_price DROP NOT NULL,
ALTER COLUMN order_quantity DROP NOT NULL,
ALTER COLUMN shipper_key DROP NOT NULL,
ALTER COLUMN order_id DROP NOT NULL,
ALTER COLUMN order_detail_id DROP NOT NULL,
ALTER COLUMN dollar_sales DROP NOT NULL;




ALTER TABLE sales_fact
ADD COLUMN order_date DATE;

